# Generated by Django 4.2.7 on 2023-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="media_file",
            field=models.ImageField(blank=True, upload_to="media/"),
        ),
    ]
