# Generated by Django 4.2.7 on 2023-11-30 19:03

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="media_file",
            field=models.ImageField(blank=True, upload_to=courses.models.resize_image),
        ),
    ]
